#!/bin/bash
which -s shc
if [ $? -eq 1 ]; then
	./setup-shc
	exit 1
else
	cp -a dev/ccAche-stable-1.0 ccAche
	shc -T -f ccAche
	rm -f ccAche
	rm -f ccAche.x.c
	sudo -p "Please enter the administrator password to continue: " mv ccAche.x /bin/ccAche
fi
echo "Why are you here? Just run \`ccAche --help\` instead." > ccAche.1
sudo mv ccAche.1 /usr/share/man/man1/ccAche.1
sudo gzip /usr/local/man/man1/ccAche.1
