#!/bin/bash
which -s shc
if [ $? -eq 1 ]; then
	./setup-shc
	exit 1
else
	cp -a dev/ccAche-stable-1.0 ccAche
	shc -T -f ccAche
	rm -f ccAche
	rm -f ccAche.x.c
	sudo -p "Please enter the administrator password to proceed: " mv ccAche.x /bin/ccAche ||
	echo "Sorry, the password was incorrect." && exit 1 ||
	echo "ccAche has been successfully installed."
fi
